---
title: "Red squirrel Berlin - maxent models"
author:
    - name: "Marius Grabow" 
      affiliation: Leibniz Institute for Zoo and Wildlife Research
      affiliation_url: https://izw-berlin.de/en/
      orcid_id: 0000-0003-0702-9642
date: "`r Sys.Date()`"
output: 
    distill::distill_article:
        highlight: kate      
        code_folding: false  
        toc: true            
        toc_depth: 2         
---

```{r setup, include=FALSE}
## You can ignore this chunk in most cases
## If you want to modify chunk options, you can do it here for all chunks or
## add the options in the repsective chunk header, e.g. `{r, message = FALSE}`
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE,
                      fig.width = 9, fig.height = 6, dpi = 500, 
                      retina = 1)
```

# Setup
```{r packages, message=FALSE, warning=FALSE}
package.list=c("tidyverse",
               "here",
               "raster",
               "sf",
               "conflicted",
               "nngeo")

for (package in package.list) {
  if (!require(package, character.only=T, quietly=T)) {
    install.packages(package)
    library(package, character.only=T)
  }
}

conflict_prefer("here", "here")
conflict_prefer("extract", "raster")
conflict_prefer("filter","dplyr")
```


# Load Data
```{r raster 10x10, message=FALSE, warning=FALSE}
Berlin_shape<-readOGR(here("data-raw",
                           "geo-raw",
                           "Berlin_shape.shp")) %>% 
                          spTransform(CRS(
                          "+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000
+ellps=GRS80 +units=m +no_defs "))

cov_stack<-readRDS(here("output","data-proc","cov10.RDS"))%>%
  stack()
cov_stack<-cov_stack[[1:12]]

template_ras_10<-raster(here("data-raw",
            "geo-raw",
            "template_raster_berlin_10m_2020_3035.tif"))

squirrels<-readRDS(here("data-raw","citizen_science","sightings_processed.RDS"))

ct_observed<-read.csv(here("data-raw","camera-trap","centroids_cameras_grid_25833.csv"))%>%
  dplyr::filter(Squirrel_Week1==1|
                Squirrel_Week2==1|
                Squirrel_Week3==1|
                Squirrel_Week4==1
                  )%>%
  st_as_sf(coords=c("xcoord_centroid_25833","ycoord_centroid_25833"),crs=25833)%>%
  st_transform(3035)


```


# MaxEnt 1 (M1)
```{r, eval=FALSE, echo=T}

#500 meter buffer around each observation
buffer500 <- st_buffer(squirrels, dist = 500) %>%
  st_union() %>%
  st_sf()

# create raster
buffer500.r1 <- buffer500 %>%
  fasterize(raster = template_ras_10, fun = "min")

# explore sampling effort
sampling_effort <- rasterize(squirrels,
                             buffer500.r1,
                             fun='count',
                             file = "species",
                             background = 0.1, 
                             overwrite =TRUE)

#sampling effort in buffer of 500m
sampling_effort<-mask(sampling_effort,buffer500)  
# background
env_cov_bg <- mask(cov_stack, buffer500.r1)

# random points (n=10000) as background
bg1 <- randomPoints(sampling_effort, n = 10000)

set.seed(2020)
# divide in training and testing sets (4:1). 20% of the observations are not included, but used for subsequent testing
group1 <- kfold(bg1, 5)
backg1_train <- bg1[group1 != 1, ]
backg1_test <- bg1[group1 == 1, ]

# divide observations  into 80% training and 20% testing 
group <- kfold(squirrels, 5)
pres_train <- as.data.frame(st_coordinates(squirrels[group !=1, ]))
pres_test <- as.data.frame(st_coordinates(squirrels[group == 1, ]))

# MaxEnt model 
maxent1 <- maxent(x = env_cov_bg, p = pres_train,
                  a = backg1_train,
                  removeDuplicates=TRUE,
                  path=here("output","maxent"),
                  factors=c('multiple_burdens',
                            'supply_green'),
                  args=c('responsecurves=true',
                  'threads=3',
                  'maximumiterations=2000',
                  'maximumbackground=100000',
                  'replicates=10',
                  'jackknife=true'))
# Prediction on full background of Berlin
pberlin.maxent1 <- predict(cov_stack, maxent1@models[[1]], progress="text")

writeRaster(pberlin.maxent1,here("output","geo-proc","habitat_maxent1.tif"),overwrite=T)
# Evaluate model
eval.maxent1 <- evaluate(pres_test, backg1_test, maxent1@models[[1]], env_cov_bg) #best model
eval.maxent1

# assign threshold
threshold(eval.maxent1)
threshold<-threshold(eval.maxent1,'spec_sens')

```

# MaxEnt 2 (M2)

```{r, eval=FALSE,echo=TRUE}
squirrels<-rbind(squirrels[,2],ct_observed[,25])

buffer500 <- st_buffer(squirrels, dist = 500) %>% st_union() %>% st_sf()
buffer500.r1 <- buffer500 %>% fasterize(raster = template_ras_10, fun = "min")

  
sampling_effort <- rasterize(squirrels,
                             buffer500.r1,
                             fun='count',
                             file = "species",
                             background = 0.1, 
                             overwrite =TRUE) 

sampling_effort<-mask(sampling_effort,buffer500)  

env_cov_bg <- mask(cov_stack, buffer500.r1)

bg1 <- randomPoints(sampling_effort, n = 10000)
set.seed(2020)
# divide in training and testing sets (4:1)
group1 <- kfold(bg1, 5)
backg1_train <- bg1[group1 != 1, ]
backg1_test <- bg1[group1 == 1, ]

# divide observations 
group <- kfold(squirrels, 5)
pres_train <- as.data.frame(st_coordinates(squirrels[group !=1, ]))
pres_test <- as.data.frame(st_coordinates(squirrels[group == 1, ]))

 
maxent2 <- maxent(x = env_cov_bg, p = pres_train,
                  a = backg1_train,
                  removeDuplicates=TRUE,
                  path=here("output","maxent2"),
                  factors=c('multiple_burdens',
                            'supply_green'),
                  args=c('responsecurves=true',
                  'threads=3',
                  'maximumiterations=2000',
                  'maximumbackground=100000',
                  'replicates=10',
                  'jackknife=true'))

pberlin.maxent2 <- predict(cov_stack, maxent2@models[[8]], progress="text")

writeRaster(pberlin.maxent2,here("output","geo-proc","habitat_maxent2.tif"),overwrite=T)

eval.maxent2 <- evaluate(pres_test, backg1_test, maxent2@models[[8]], env_cov_bg)
eval.maxent2
```





***

<details><summary>Session Info</summary>

```{r sessionInfo}
## DO NOT REMOVE!
## We store the settings of your computer and the current versions of the
## packages used to allow for reproducibility
Sys.time()
#git2r::repository() ## uncomment if you are using GitHub
sessionInfo()
```

</details>

